toc:
  - title: PX-Backup documentation
    link: https://1.0.backup.docs.portworx.com
  - title: The Rock paper scissors API
    link: /sample-works/api
  - title: Deploy a static website on Google Cloud Platform
    link: /sample-works/create-a-statamic-web-server-on-google-cloud-platform/
    pages:
      - page: Create a Google Cloud Platform Compute Engine instance
        link: /sample-works/create-a-statamic-web-server-on-google-cloud-platform/create-a-google-cloud-platform-compute-engine-instance
      - page: Create a key and add it to GCP
        link: /sample-works/create-a-statamic-web-server-on-google-cloud-platform/create-a-key-and-add-it-to-gcp
      - page: Install web server dependencies
        link: /sample-works/create-a-statamic-web-server-on-google-cloud-platform/install-web-server-dependencies
      - page: Add GitHub access to your VM
        link: /sample-works/create-a-statamic-web-server-on-google-cloud-platform/add-github-access-to-your-vm
      - page: Clone your repository into your web server
        link: /sample-works/create-a-statamic-web-server-on-google-cloud-platform/clone-your-repository-into-your-web-server
      - page: Configure Apache
        link: /sample-works/create-a-statamic-web-server-on-google-cloud-platform/configure-apache
      - page: Create a new virtual host configuration
        link: /sample-works/create-a-statamic-web-server-on-google-cloud-platform/create-a-new-virtual-host-configuration
  - title: Vertica on AWS backup and restore guide
    link: https://www.vertica.com/docs/8.1.x/HTML/index.htm#Authoring/BackupAndRestoreVerticaOnAWS/Introduction.htm
    pages: 
      - page: K-Safe cluster configuration
        link: https://www.vertica.com/docs/8.1.x/HTML/index.htm#Authoring/BackupAndRestoreVerticaOnAWS/SingleNodeFailure.htm
      - page: Full backup
        link: https://www.vertica.com/docs/8.1.x/HTML/index.htm#Authoring/BackupAndRestoreVerticaOnAWS/FullBackup.htm
      - page: Restore from a full backup
        link: https://www.vertica.com/docs/8.1.x/HTML/index.htm#Authoring/BackupAndRestoreVerticaOnAWS/RestoreFromFullBackup.htm
      - page: Hard-link backups on AWS RAID-0
        link: https://www.vertica.com/docs/8.1.x/HTML/index.htm#Authoring/BackupAndRestoreVerticaOnAWS/HardLinkBackupOnAWSRAID.htm
      - page: Restore from a hard-link backup
        link: https://www.vertica.com/docs/8.1.x/HTML/index.htm#Authoring/BackupAndRestoreVerticaOnAWS/RestoreFromHardLinkBackup.htm